<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="utf-8" />';
echo '<meta name="viewport" content="initial-scale=1, width=device-width" />';
echo '';
echo '<link rel="stylesheet" href="./global.css" />';
echo '<link rel="stylesheet" href="./index.css" />';
echo '<link';
echo 'rel="stylesheet"';
echo 'href="https://fonts.googleapis.com/css2?family=Anton:wght@400&display=swap"';
echo '/>';
echo '<link';
echo 'rel="stylesheet"';
echo 'href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;600;700;900&display=swap"';
echo '/>';
echo '<link';
echo 'rel="stylesheet"';
echo 'href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;900&display=swap"';
echo '/>';
echo '<link';
echo 'rel="stylesheet"';
echo 'href="https://fonts.googleapis.com/css2?family=Font Awesome 5 Free:wght@400&display=swap"';
echo '/>';
echo '<link';
echo 'rel="stylesheet"';
echo 'href="https://fonts.googleapis.com/css2?family=Antic Slab:wght@400&display=swap"';
echo '/>';
echo '</head>';
echo '<body>';
echo '<div class="home">';
echo '<div class="logros">';
echo '<div class="logros-child"></div>';
echo '<div class="logros-item"></div>';
echo '<div class="logros-inner"></div>';
echo '<div class="ellipse-div"></div>';
echo '<div class="logros-child1"></div>';
echo '<div class="logros-child2"></div>';
echo '<div class="nosotros">nosotros</div>';
echo '<div class="logros1">logros</div>';
echo '<div class="div">50%</div>';
echo '<div class="div1">70%</div>';
echo '<div class="div2">90%</div>';
echo '<div class="mejora-en-la">Mejora en la Concentración</div>';
echo '<div class="desarrollo-de-habilidades">';
echo 'Desarrollo de Habilidades de Organización';
echo '</div>';
echo '<div class="reduccin-del-estrs">Reducción del Estrés y la Ansiedad</div>';
echo '</div>';
echo '<div class="prioridad">';
echo '<img class="burbujas-icon" alt="" src="./public/burbujas@2x.png" />';
echo '';
echo '<img class="burbujas-icon1" alt="" src="./public/burbujas@2x.png" />';
echo '';
echo '<div class="destacar">destacar</div>';
echo '<div class="nuestra-prioridad">Nuestra prioridad</div>';
echo '<div class="prioridad-child"></div>';
echo '<div class="prioridad-item"></div>';
echo '<div class="prioridad-inner"></div>';
echo '<div class="rectangle-div"></div>';
echo '<img class="medal-2-icon" alt="" src="./public/medal-2@2x.png" />';
echo '';
echo '<div class="precio">Precio</div>';
echo '<div class="calidad">Calidad</div>';
echo '<div class="experiencia">Experiencia</div>';
echo '<div class="innovacin">innovación</div>';
echo '<div class="priorizamos-la-calidad">';
echo 'priorizamos la calidad sin elevar los costos. Ofrecemos servicios de';
echo 'alta calidad a precios accesibles, garantizando un valor excepcional';
echo 'en cada experiencia.';
echo '</div>';
echo '<div class="nos-destacamos-por">';
echo 'nos destacamos por ofrecer productos/servicios de calidad inigualable.';
echo 'Desde el inicio hasta el final, nos esforzamos por superar tus';
echo 'expectativas.';
echo '</div>';
echo '<div class="en-brainwave-con">';
echo 'En brainwave, con años de liderazgo en [tu industria], brindamos';
echo 'servicios perfeccionados. Confía en nuestra experiencia para una';
echo 'atención destacada y dedicada.';
echo '</div>';
echo '<div class="destacamos-por-integrar">';
echo 'destacamos por integrar tecnología e innovación de vanguardia en todos';
echo 'nuestros procesos, Desde soluciones tecnológicas avanzadas hasta';
echo 'enfoques innovadores.';
echo '</div>';
echo '<div class="line-div"></div>';
echo '<div class="prioridad-child1"></div>';
echo '<div class="prioridad-child2"></div>';
echo '<div class="prioridad-child3"></div>';
echo '<img class="image-3-icon" alt="" src="./public/image-3@2x.png" />';
echo '';
echo '<img class="image-4-icon" alt="" src="./public/image-4@2x.png" />';
echo '';
echo '<img class="image-2-icon" alt="" src="./public/image-2@2x.png" />';
echo '</div>';
echo '<div class="servicios">';
echo '<div class="que-puedes-hacer">¿Que puedes hacer?</div>';
echo '<div class="todo-lo-que">Todo lo que te ofrecemos</div>';
echo '<div class="polygon-parent" id="groupContainer">';
echo '<img class="group-child" alt="" src="./public/polygon-8.svg" />';
echo '';
echo '<img class="group-item" alt="" src="./public/polygon-5.svg" />';
echo '';
echo '<div class="group-inner"></div>';
echo '<div class="libros">Libros</div>';
echo '<img class="book-1-icon" alt="" src="./public/book-1@2x.png" />';
echo '</div>';
echo '<div class="polygon-group" id="groupContainer1">';
echo '<img class="group-item" alt="" src="./public/polygon-8.svg" />';
echo '';
echo '<img class="group-item" alt="" src="./public/polygon-5.svg" />';
echo '';
echo '<div class="group-child2"></div>';
echo '<div class="workshops">workshops</div>';
echo '<img';
echo 'class="workshop-1-icon"';
echo 'alt=""';
echo 'src="./public/workshop-1@2x.png"';
echo '/>';
echo '</div>';
echo '<div class="polygon-container" id="groupContainer2">';
echo '<img class="group-item" alt="" src="./public/polygon-8.svg" />';
echo '';
echo '<img class="group-item" alt="" src="./public/polygon-5.svg" />';
echo '';
echo '<div class="group-child5"></div>';
echo '<div class="podcasts">podcasts</div>';
echo '<img';
echo 'class="microphone-1-1"';
echo 'alt=""';
echo 'src="./public/microphone-1-1@2x.png"';
echo '/>';
echo '</div>';
echo '<div class="group-div" id="groupContainer3">';
echo '<img class="group-item" alt="" src="./public/polygon-8.svg" />';
echo '';
echo '<img class="group-item" alt="" src="./public/polygon-5.svg" />';
echo '';
echo '<div class="group-child8"></div>';
echo '<div class="psicologos">psicologos</div>';
echo '<img';
echo 'class="mental-health-1-icon"';
echo 'alt=""';
echo 'src="./public/mentalhealth-1@2x.png"';
echo '/>';
echo '</div>';
echo '<div class="polygon-parent1" id="groupContainer4">';
echo '<img class="group-item" alt="" src="./public/polygon-8.svg" />';
echo '';
echo '<img class="group-item" alt="" src="./public/polygon-5.svg" />';
echo '';
echo '<div class="group-child11"></div>';
echo '<div class="articulos">Articulos</div>';
echo '<img';
echo 'class="articles-1-icon"';
echo 'alt=""';
echo 'src="./public/articles-1@2x.png"';
echo '/>';
echo '</div>';
echo '<img class="extra-icon" alt="" src="./public/extra.svg" />';
echo '</div>';
echo '<div class="nuestra-visin">';
echo '<div class="nuestra-visin-child"></div>';
echo '<div class="futuro">Futuro</div>';
echo '<div class="nuestra-visin1">Nuestra visión</div>';
echo '<div class="en-brainwave-trabajamos">';
echo 'En Brainwave, trabajamos para construir un mundo más comprensivo y';
echo 'solidario al cambiar la narrativa en torno al TDAH. Nos esforzamos por';
echo 'transformar este trastorno de un estigma a una fuerza única, creando';
echo 'conexiones más profundas, aumentando la conciencia social y brindando';
echo 'un apoyo efectivo para enfrentar el día a día.';
echo '</div>';
echo '<div class="boton-secundario">';
echo '<div class="boton-secundario-child"></div>';
echo '<div class="button">ver</div>';
echo '</div>';
echo '<img';
echo 'class="visionary-1-icon"';
echo 'alt=""';
echo 'src="./public/visionary-1@2x.png"';
echo '/>';
echo '</div>';
echo '<div class="nav">';
echo '<div class="boton-primario">';
echo '<div class="boton-primario-child"></div>';
echo '<div class="button1">rEGISTRO</div>';
echo '</div>';
echo '<div class="no-te-cortes-desata-tu-creati-parent">';
echo '<div class="no-te-cortes-container">';
echo '<span class="no-te-cortes-container1">';
echo '<p class="no-te-cortes">¡No te cortes!</p>';
echo '<p class="no-te-cortes">Desata tu creatividad sin límites</p>';
echo '</span>';
echo '</div>';
echo '<div class="brainwave">';
echo '<span class="brainwave-txt">';
echo '<p class="no-te-cortes">&nbsp;</p>';
echo '<p class="brainwave1">Brainwave</p>';
echo '</span>';
echo '</div>';
echo '<div class="welcome-to">Welcome to</div>';
echo '<div class="registro-2">';
echo '<div class="buscador"></div>';
echo '<div class="registro-2-child"></div>';
echo '<b class="unete-a-brainwave">Unete a brainwave</b>';
echo '<b class="introduce-tu-email">Introduce tu email</b>';
echo '</div>';
echo '</div>';
echo '<div class="saturn-1"></div>';
echo '<div class="buscador1"></div>';
echo '<img class="logo-icon" alt="" src="./public/logo.svg" />';
echo '';
echo '<img';
echo 'class="img-20231217-wa0048-1-icon"';
echo 'alt=""';
echo 'src="./public/img20231217wa0048-1@2x.png"';
echo '/>';
echo '';
echo '<img class="search-icon" alt="" src="./public/search@2x.png" />';
echo '';
echo '<div class="servicios1">Servicios</div>';
echo '<div class="apoyo">Apoyo</div>';
echo '<div class="nosotros1">Nosotros</div>';
echo '<div class="plantilla">';
echo '<img';
echo 'class="rompecabezas-1-icon"';
echo 'alt=""';
echo 'src="./public/rompecabezas-1@2x.png"';
echo '/>';
echo '';
echo '<img';
echo 'class="rompecabezas-2-icon"';
echo 'alt=""';
echo 'src="./public/rompecabezas-2@2x.png"';
echo '/>';
echo '';
echo '<img';
echo 'class="rompecabezas-6-icon"';
echo 'alt=""';
echo 'src="./public/rompecabezas-6@2x.png"';
echo '/>';
echo '';
echo '<img';
echo 'class="rompecabezas-3-icon"';
echo 'alt=""';
echo 'src="./public/rompecabezas-3@2x.png"';
echo '/>';
echo '';
echo '<img';
echo 'class="rompecabezas-8-icon"';
echo 'alt=""';
echo 'src="./public/rompecabezas-8@2x.png"';
echo '/>';
echo '';
echo '<img';
echo 'class="rompecabezas-9-icon"';
echo 'alt=""';
echo 'src="./public/rompecabezas-9@2x.png"';
echo '/>';
echo '';
echo '<img';
echo 'class="rompecabezas-10-icon"';
echo 'alt=""';
echo 'src="./public/rompecabezas-9@2x.png"';
echo '/>';
echo '';
echo '<img';
echo 'class="rompecabezas-7-icon"';
echo 'alt=""';
echo 'src="./public/rompecabezas-3@2x.png"';
echo '/>';
echo '';
echo '<img';
echo 'class="rompecabezas-4-icon"';
echo 'alt=""';
echo 'src="./public/rompecabezas-4@2x.png"';
echo '/>';
echo '';
echo '<img';
echo 'class="rompecabezas-5-icon"';
echo 'alt=""';
echo 'src="./public/rompecabezas-1@2x.png"';
echo '/>';
echo '</div>';
echo '<div class="nav1">';
echo '<img';
echo 'class="img-20231217-wa0048-1-icon1"';
echo 'alt=""';
echo 'src="./public/img20231217wa0048-1@2x.png"';
echo '/>';
echo '';
echo '<div class="servicios2" id="serviciosText">Servicios</div>';
echo '<div class="recursos">recursos</div>';
echo '<div class="nosotros2" id="nosotrosText">Nosotros</div>';
echo '<img';
echo 'class="lluvia-de-ideas-2-icon"';
echo 'alt=""';
echo 'src="./public/lluviadeideas-2@2x.png"';
echo '/>';
echo '';
echo '<div class="boton-primario" id="botonPrimarioContainer">';
echo '<div class="boton-primario-item"></div>';
echo '<div class="button1">rEGISTRO</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="footer">';
echo '<div class="brainwave2">BRAINWAVE</div>';
echo '<div class="footer-child"></div>';
echo '<img class="misc-icon" alt="" src="./public/misc.svg" />';
echo '';
echo '<div class="contacto">';
echo '<div class="contacto-child"></div>';
echo '<div class="subscribe">Subscribe</div>';
echo '<div class="div3"></div>';
echo '<div class="div4"></div>';
echo '</div>';
echo '<div class="footer12">';
echo '<img';
echo 'class="footer12-child"';
echo 'alt=""';
echo 'src="./public/rectangle-5@2x.png"';
echo '/>';
echo '';
echo '<img class="footer12-item" alt="" src="./public/rectangle-4@2x.png" />';
echo '';
echo '<img';
echo 'class="footer12-inner"';
echo 'alt=""';
echo 'src="./public/rectangle-3@2x.png"';
echo '/>';
echo '';
echo '<div class="botn-contacto">';
echo '<div class="botn-contacto-child"></div>';
echo '<div class="contactanos">Contactanos</div>';
echo '</div>';
echo '<div class="redes-sociales">Redes Sociales</div>';
echo '<div class="politica-de-privacidad">Politica de privacidad</div>';
echo '<div class="disclamer">Disclamer</div>';
echo '<div class="terminos-de-uso">Terminos de uso</div>';
echo '</div>';
echo '<div class="calle-de-la-container">';
echo '<p class="no-te-cortes">';
echo '123 Calle de la Serenidad, Distrito Creativo';
echo '</p>';
echo '<p class="no-te-cortes">&nbsp;</p>';
echo '</div>';
echo '<div class="brainwaveusgmailcom">Brain.wave.us@gmail.com</div>';
echo '<div class="brainwave-copyright-">';
echo 'brainwave copyright - own elements';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<div id="registroContainer" class="popup-overlay" style="display: none">';
echo '<div class="registro">';
echo '<div class="plantilla1">';
echo '<img class="background-icon" alt="" src="./public/background.svg" />';
echo '';
echo '<div class="boton-secundario1">';
echo '<div class="boton-secundario-item"></div>';
echo '<div class="button3">Entrar</div>';
echo '</div>';
echo '<div class="register">';
echo '<span class="register-txt">';
echo '<span>R</span>';
echo '<span class="egister">egister</span>';
echo '</span>';
echo '</div>';
echo '<div class="password">password</div>';
echo '<div class="div5">***************</div>';
echo '<img class="plantilla-child" alt="" />';
echo '';
echo '<img';
echo 'class="espectaculo-1-icon"';
echo 'alt=""';
echo 'src="./public/espectaculo-1@2x.png"';
echo '/>';
echo '';
echo '<div class="contrasea-olvidada">contraseña olvidada</div>';
echo '<div class="ya-tienes-cuenta">ya tienes cuenta?</div>';
echo '<div class="login" id="popuploginText">login</div>';
echo '<div class="email">email</div>';
echo '<div class="first-name">FIRST NAME</div>';
echo '<div class="last-name">LAST NAME</div>';
echo '<img class="plantilla-item" alt="" />';
echo '';
echo '<img class="plantilla-inner" alt="" />';
echo '';
echo '<img class="line-icon" alt="" />';
echo '';
echo '<div class="div6">+</div>';
echo '<img class="icon" alt="" src="./public/170025536383721931-1@2x.png" />';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<script>';
echo 'var popuploginText = document.getElementById("popuploginText");';
echo 'if (popuploginText) {';
echo 'popuploginText.addEventListener("click", function (e) {';
echo '// Please sync "Login" to the project';
echo '});';
echo '}';
echo '';
echo 'var groupContainer = document.getElementById("groupContainer");';
echo 'if (groupContainer) {';
echo 'groupContainer.addEventListener("click", function (e) {';
echo '// Please sync "Apoyo" to the project';
echo '});';
echo '}';
echo '';
echo 'var groupContainer1 = document.getElementById("groupContainer1");';
echo 'if (groupContainer1) {';
echo 'groupContainer1.addEventListener("click", function (e) {';
echo '// Please sync "Servicios" to the project';
echo '});';
echo '}';
echo '';
echo 'var groupContainer2 = document.getElementById("groupContainer2");';
echo 'if (groupContainer2) {';
echo 'groupContainer2.addEventListener("click", function (e) {';
echo '// Please sync "Podcasts" to the project';
echo '});';
echo '}';
echo '';
echo 'var groupContainer3 = document.getElementById("groupContainer3");';
echo 'if (groupContainer3) {';
echo 'groupContainer3.addEventListener("click", function (e) {';
echo '// Please sync "Psicólogos" to the project';
echo '});';
echo '}';
echo '';
echo 'var groupContainer4 = document.getElementById("groupContainer4");';
echo 'if (groupContainer4) {';
echo 'groupContainer4.addEventListener("click", function (e) {';
echo '// Please sync "Apoyo" to the project';
echo '});';
echo '}';
echo '';
echo 'var serviciosText = document.getElementById("serviciosText");';
echo 'if (serviciosText) {';
echo 'serviciosText.addEventListener("click", function (e) {';
echo '// Please sync "Servicios" to the project';
echo '});';
echo '}';
echo '';
echo 'var nosotrosText = document.getElementById("nosotrosText");';
echo 'if (nosotrosText) {';
echo 'nosotrosText.addEventListener("click", function (e) {';
echo '// Please sync "About us" to the project';
echo '});';
echo '}';
echo '';
echo 'var botonPrimarioContainer = document.getElementById("botonPrimarioContainer");';
echo 'if (botonPrimarioContainer) {';
echo 'botonPrimarioContainer.addEventListener("click", function () {';
echo 'var popup = document.getElementById("registroContainer");';
echo 'if (!popup) return;';
echo 'var popupStyle = popup.style;';
echo 'if (popupStyle) {';
echo 'popupStyle.display = "flex";';
echo 'popupStyle.zIndex = 100;';
echo 'popupStyle.backgroundColor = "rgba(113, 113, 113, 0.3)";';
echo 'popupStyle.alignItems = "center";';
echo 'popupStyle.justifyContent = "center";';
echo '}';
echo 'popup.setAttribute("closable", "");';
echo '';
echo 'var onClick =';
echo 'popup.onClick ||';
echo 'function (e) {';
echo 'if (e.target === popup && popup.hasAttribute("closable")) {';
echo 'popupStyle.display = "none";';
echo '}';
echo '};';
echo 'popup.addEventListener("click", onClick);';
echo '});';
echo '}';
echo '</script>';
echo '</body>';
echo '</html>';
echo '';
?>